### ISSUE TITLE
explicit list of dependecies

### ISSUE THREAD

**Issue by Sinan81** [rbld/rebuild#4]
Hi I am wondering if you can provide an explicit list of dependencies like the one below on the main README.md file.

- ruby
- ruby-dev
- gem
- gem-dev
- gem rake

I can imagine many people being discouraged from checking out 'rbld' because 'gem install rbld' just doesn't work at the first try.

**Comment by dmitryfleytman** [comment]
Done at a75d32efa31ad89ed4163b2562b4c696715c9b44.

Thanks!
