### ISSUE TITLE
make file for hello.c

### ISSUE THREAD

**Issue by Sinan81** [rbld/rebuild#5]
Hi, I am wondering if you can provide a **makefile** for the hello.c example. As obvious as this might be to me or to the developers of rbld, I think many people will be discouraged by the absence of a such simple example, and simply giving rbld a try.

Regards,

**Comment by 20lives** [comment]
you can find it in here:
**cli/tests/hello**
https://github.com/rbld/rebuild/tree/master/cli/tests/hello

**Comment by Sinan81** [comment]
Thanks!
