### ISSUE TITLE
make: /gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-: not found

### ISSUE THREAD

**Issue by Sinan81** [rbld/rebuild#6]
I am getting this error in rpi development environment. I am wondering if someone can point out what went wrong here. Here are the commands.
First, I switched to rpi dev environment then issued 'make':
`user@host ~/rbld_experiments $ rbld run rpi-raspbian:v001
>>> rebuild env rpi-raspbian-v001 interactive
>>> Press CTRL-D do leave
test@rpi-raspbian-v001 $ make
/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf- hello.c
make: /gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-: Command not found
makefile:3: recipe for target 'main' failed
make: *** [main] Error 127`

note that 'env' command reveals "CC=/gcc-linaro-arm-linux-gnueabihf-raspbian-x64/bin/arm-linux-gnueabihf-"

**Comment by 20lives** [comment]
are you trying an environment form the hub (rbld deploy rpi-raspbian:v001) or you have created this environment yourself?

**Comment by Sinan81** [comment]
I am using "rbld deploy rpi-raspbian:v001"

**Comment by 20lives** [comment]
are you using this make file?
https://github.com/rbld/rebuild/blob/master/cli/tests/hello/Makefile

**Comment by Sinan81** [comment]
Yes, after using that file, 'make' works. It was just that i was using $CC as opposed to ${CC}gcc
thanks.
